name: mediaflow
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/



fonts:
    - family: GR
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500

          

    - family: GB
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800
          
    - family: GH
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500
